import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'First next app',
  description: 'Generated by create next app',
}

  const  RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          <ul className='flex'>
            <li><a href="#">Home</a></li>
            <li><a href="#">About</a></li>
            <li><a href="#">Blog</a></li>
          </ul>
        </nav>
        {children}
        <footer>
          <small>ALl right reserved by HERO</small>
        </footer>
        </body>
    </html>
  )
}


export default RootLayout;